In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
sns.set_style('darkgrid')
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
train_data=pd.read_csv('Train.csv')
train_data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
train_data['area_type'].value_counts()

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64

In [4]:
# train_data['availability'].value_counts()

In [5]:
# train_data['location'].value_counts()

In [6]:
# train_data['size'].value_counts()

In [7]:
train_data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [8]:
# train_data['society'].value_counts()
train_data.shape

(13320, 9)

In [9]:
train_data.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [10]:
train_data['society'].fillna("MissingSociety",inplace=True)

In [11]:
train_data.isnull().sum()

area_type         0
availability      0
location          1
size             16
society           0
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [12]:
train_data.dropna(subset=['location'],inplace=True)

In [13]:
train_data['bath'] = train_data.groupby(['location']).transform(lambda x: x.fillna(x.median()))['bath']
train_data['balcony'] = train_data.groupby(['location']).transform(lambda x: x.fillna(x.median()))['balcony']

In [14]:
train_data.isnull().sum()

area_type        0
availability     0
location         0
size            16
society          0
total_sqft       0
bath             1
balcony         45
price            0
dtype: int64

In [15]:
train_data['bath'].fillna(train_data['bath'].median(),inplace=True)
train_data['balcony'].fillna(train_data['balcony'].median(),inplace=True)

In [16]:
train_data['size']=train_data['size'].apply(lambda x:str(x).split(" ")[0]).astype(float)

In [17]:
train_data['size'] = train_data.groupby(['location']).transform(lambda x: x.fillna(x.median()))['size']

In [18]:
train_data.dropna(subset=['size'],inplace=True)

In [19]:
# train_data.isnull().sum()
train_data.shape

(13318, 9)

In [20]:
train_data.head(3)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2.0,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4.0,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3.0,MissingSociety,1440,2.0,3.0,62.00

In [21]:
train_data.drop('availability',1,inplace=True)

In [22]:
train_data.head(3)

,area_type,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,Electronic City Phase II,2.0,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Chikka Tirupathi,4.0,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Uttarahalli,3.0,MissingSociety,1440,2.0,3.0,62.00

In [23]:
train_data['Location']=train_data['location']+" "+train_data['society']

In [24]:
areatype=pd.get_dummies(train_data[['area_type']],drop_first=True)

In [25]:
areatype.head()

,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,0,0,1
1,0,1,0
2,0,0,0
3,0,0,1
4,0,0,1

In [26]:
df=pd.concat([train_data,areatype],axis=1)

In [27]:
df.drop('area_type',1,inplace=True)

In [28]:
df.drop(['location','society'],1,inplace=True)

In [29]:
df.head()

,size,total_sqft,bath,balcony,price,Location,area_type_Carpet Area,area_type_Plot Area,area_type_Super built-up Area
0,2.0,1056,2.0,1.0,39.07,Electronic City Phase II Coomee,0,0,1
1,4.0,2600,5.0,3.0,120.00,Chikka Tirupathi Theanmp,0,1,0
2,3.0,1440,2.0,3.0,62.00,Uttarahalli MissingSociety,0,0,0
3,3.0,1521,3.0,1.0,95.00,Lingadheeranahalli Soiewre,0,0,1
4,2.0,1200,2.0,1.0,51.00,Kothanur MissingSociety,0,0,1

In [54]:
df.dtypes

size                              float64
total_sqft                         object
bath                              float64
balcony                           float64
price                             float64
Location                           object
area_type_Carpet  Area              uint8
area_type_Plot  Area                uint8
area_type_Super built-up  Area      uint8
dtype: object

In [60]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [62]:
# df['total_sqft'].value_counts()

1200                 843
1100                 221
1500                 205
2400                 196
600                  180
1000                 172
1350                 133
1050                 123
1300                 117
1250                 114
900                  112
1400                 108
1800                 104
1150                 101
1600                 100
1140                  91
2000                  83
1450                  70
1650                  69
800                   67
1075                  66
3000                  66
1020                  63
2500                  62
1125                  60
1160                  60
1550                  60
950                   59
1180                  58
1700                  58
1260                  57
1255                  56
1220                  55
1080                  55
1070                  53
750                   52
700                   52
1225                  48
1175                  48
4000                  48
2100                  46
1240                  46
1320                  46
1230                  45
1060                  45
1210                  44
850                   43
1280                  42
1185                  41
1270                  41
1170                  40
1410                  40
1190                  40
1750                  39
1025                  38
1330                  38
1290                  37
1850                  37
1310                  37
1065                  36
1194                  36
1215                  35
1090                  35
500                   34
2700                  33
1115                  33
1360                  33
3500                  32
1900                  32
1120                  32
1464                  32
2200                  31
1340                  31
1530                  31
1430                  31
1205                  31
1560                  30
1035                  30
1165                  30
3600                  29
1130                  29
1145                  29
1128                  29
1275                  28
1355                  28
2800                  28
1040                  28
1420                  27
1105                  27
1155                  27
1680                  27
1245                  25
650                   25
1590                  25
1216                  25
1460                  25
1760                  25
1305                  24
1475                  24
2600                  24
1010                  24
1440                  23
883                   23
1575                  23
1110                  23
1030                  23
1495                  22
985                   22
1246                  22
1315                  21
1370                  21
1610                  21
1015                  21
1243                  21
3200                  21
1325                  21
1385                  21
525                   21
5000                  21
1027                  21
1470                  21
660                   20
925                   20
1540                  20
1480                  20
1390                  20
550                   20
1570                  19
1520                  19
920                   19
1645                  19
1265                  19
1365                  19
1640                  19
1665                  18
940                   18
1525                  18
1012                  18
1196                  18
975                   18
4800                  18
1345                  18
1820                  18
1095                  18
1195                  18
980                   18
1485                  18
2072                  18
1157                  17
1375                  17
1232                  17
960                   17
400                   17
1295                  17
3300                  16
1135                  16
1720                  16
1830                  16
1235                  16
1425                  16
1045                  16
2300                  16
645                   16
1490                  16
935                   16
1655                  16
1197                  16
1418                  16
1740                  15
1153                  15
1285                  15
1152                  15
1380                  15
1580                  15
1660                  15
1920                  15
630                   15
4500                  15
1116                  15
1085                  15
1950                  15
720                   14
905                   14
675                   14
450                   14
1141                  14
1630                  14
1445                  14
1595                  14
1535                  13
1615                  13
840                   13
1710                  13
3800                  13
2215                  13
1005                  13
1730                  13
1510                  13
1282                  13
1875                  13
970                   13
2250                  13
1314                  13
1625                  13
1690                  13
1082                  13
3900                  13
1252                  12
1565                  12
2900                  12
1890                  12
1151                  12
1007                  12
1455                  12
1339                  12
1056                  12
1435                  12
1296                  12
1033                  12
1691                  12
1843                  12
3100                  12
1404                  12
1162                  11
1174                  11
1639                  11
984                   11
540                   11
845                   11
1452                  11
2150                  11
965                   11
1405                  11
1685                  11
1346                  11
1206                  11
1804                  11
1515                  11
2350                  10
4200                  10
770                   10
620                   10
1308                  10
918                   10
880                   10
995                   10
1555                  10
1465                  10
957                   10
1810                  10
1198                  10
1620                  10
760                   10
1063                  10
930                   10
3596                  10
3400                  10
1256                  10
1161                  10
1415                  10
1223                   9
1693                   9
890                    9
1419                   9
1715                   9
1745                   9
674                    9
825                    9
1725                   9
1108                   9
6000                   9
2750                   9
1482                   9
2475                   9
1224                   9
3250                   9
3150                   9
1047                   9
705                    9
1724                   9
945                    9
1870                   9
1092                   9
1756                   9
1605                   9
1113                   9
3750                   9
910                    9
1186                   9
1790                   9
2790                   9
2180                   9
1222                   9
780                    9
1156                   9
1322                   8
3122                   8
4400                   8
1395                   8
1026                   8
1447                   8
1192                   8
1335                   8
1221                   8
1703                   8
1636                   8
1835                   8
1705                   8
1352                   8
1178                   8
1476                   8
1299                   8
1146                   8
812                    8
2650                   8
5400                   8
2990                   8
870                    8
1187                   8
680                    8
656                    8
2145                   8
1088                   8
1133                   8
1089                   8
875                    8
1163                   8
1670                   8
1532                   8
990                    8
1349                   7
1112                   7
1880                   7
1041                   7
2050                   7
1762                   7
1840                   7
1251                   7
1718                   7
1917                   7
1453                   7
1166                   7
1036                   7
1199                   7
820                    7
1306                   7
708                    7
1427                   7
1143                   7
1847                   7
1357                   7
1374                   7
1069                   7
7500                   7
1910                   7
1276                   7
1101                   7
1272                   7
1392                   7
1179                   7
1044                   7
1096                   7
1254                   7
1132                   7
1183                   7
982                    7
1093                   7
1342                   7
1508                   7
615                    7
1564                   7
1397                   7
1545                   7
1277                   7
1262                   7
1139                   7
1062                   6
1167                   6
929                    6
1127                   6
1717                   6
2280                   6
440                    6
1484                   6
1855                   6
2010                   6
1053                   6
1991                   6
1102                   6
1571                   6
625                    6
1785                   6
1126                   6
654                    6
1278                   6
1372                   6
2040                   6
1719                   6
933                    6
2690                   6
1303                   6
1286                   6
1411                   6
2425                   6
1697                   6
924                    6
1213                   6
1735                   6
1107                   6
936                    6
1846                   6
1084                   6
2480                   6
1173                   6
520                    6
1770                   6
1181                   6
2275                   6
1787                   6
530                    6
710                    6
1583                   6
560                    6
1362                   6
1333                   6
1780                   6
2225                   6
1028                   6
1541                   6
1083                   6
830                    6
1614                   6
1257                   6
1755                   6
1247                   6
3895                   6
1936                   6
1016                   6
1019                   6
1602                   6
1893                   6
1242                   6
605                    6
1268                   6
1274                   6
1176                   6
1656                   6
1304                   6
7000                   6
810                    6
610                    6
1512                   6
1675                   6
2774                   6
1635                   6
1313                   6
1451                   6
860                    6
1856                   6
740                    5
1142                   5
1188                   5
2710                   5
1935                   5
545                    5
1868                   5
1749                   5
1055                   5
1444                   5
1662                   5
1408                   5
1293                   5
2850                   5
1403                   5
4050                   5
1057                   5
1021                   5
1586                   5
1329                   5
1309                   5
1436                   5
1458                   5
510                    5
1505                   5
1076                   5
919                    5
1364                   5
410                    5
1123                   5
2254                   5
1208                   5
2830 - 2882            5
1825                   5
1297                   5
1826                   5
1241                   5
1559                   5
1738                   5
1801                   5
1204                   5
1226                   5
1231                   5
1326                   5
1930                   5
1798                   5
865                    5
1573                   5
2340                   5
1354                   5
1865                   5
420                    5
1884                   5
1862                   5
2360                   5
4395                   5
2119                   5
1424                   5
1098                   5
1664                   5
1683                   5
1457                   5
1263                   5
1184                   5
1585                   5
1852                   5
1009                   5
3450                   5
1052                   5
1077                   5
635                    5
1533                   5
1031                   5
1148                   5
1754                   5
715                    5
907                    5
1267                   5
1344                   5
1022                   5
1358                   5
1168                   5
1925                   5
1253                   5
1351                   5
1269                   5
915                    5
1765                   5
1328                   5
1567                   5
640                    5
1109                   5
1654                   5
1244                   5
1432                   4
2805                   4
1067                   4
2450                   4
1634                   4
1238                   4
1037                   4
1459                   4
967                    4
1569                   4
1933                   4
1332                   4
1291                   4
1059                   4
1158                   4
1046                   4
1074                   4
360                    4
1118                   4
1732                   4
3520                   4
814                    4
1537                   4
1386                   4
1201                   4
1980                   4
1008                   4
755                    4
1234                   4
1711                   4
1776                   4
1449                   4
1466                   4
416                    4
955                    4
1885                   4
1608                   4
1938                   4
1842                   4
2439                   4
2560                   4
1058                   4
3700                   4
662                    4
1752.12                4
1334                   4
8000                   4
1259                   4
1171                   4
1806                   4
418                    4
1702                   4
1881                   4
1767                   4
1203                   4
1616                   4
3850                   4
877                    4
1407                   4
1945                   4
1611                   4
2135                   4
884                    4
1134                   4
1592                   4
1073                   4
2830                   4
927                    4
2070                   4
1975                   4
1091                   4
1965                   4
1061                   4
946                    4
1489                   4
1318                   4
1081                   4
1236                   4
2640                   4
902                    4
2273                   4
2240                   4
1258                   4
2760                   4
1207                   4
1111                   4
1034                   4
1394                   4
1149                   4
1891                   4
1353                   4
1104                   4
966                    4
1072                   4
1051                   4
996                    4
595                    4
1517                   4
1504                   4
914                    4
1219                   4
1563                   4
602                    4
1202                   4
1279                   4
460                    4
665                    4
10000                  4
1494                   4
4100                   4
795                    4
992                    4
1976                   4
4750                   4
580                    4
1169                   4
497                    4
972                    4
1864                   4
3436                   4
1708                   4
1079                   4
12000                  4
1695                   4
1904                   4
861                    4
1837                   4
1521                   4
1929                   4
921                    4
1596                   4
1698                   4
1795                   4
775                    4
2160                   4
1343                   4
993                    4
1367                   4
1138                   4
1086                   3
1182                   3
1498                   3
2230                   3
2357                   3
670                    3
2770                   3
648                    3
1588                   3
1017                   3
1144                   3
1347                   3
2289                   3
1632                   3
2264                   3
1788                   3
2065                   3
1071                   3
1704                   3
1678                   3
1191                   3
1599                   3
2367                   3
1777.26                3
1845                   3
9600                   3
1491                   3
1758                   3
1024                   3
2502                   3
2422                   3
1652                   3
1496                   3
658                    3
1726                   3
663                    3
1819                   3
1018                   3
2106                   3
1942                   3
1336                   3
1896                   3
6500                   3
702                    3
2020                   3
690                    3
1672                   3
2330                   3
7200                   3
3050                   3
1227                   3
2559                   3
425                    3
1768                   3
1985                   3
1006                   3
1576                   3
2087.01                3
1536                   3
1311                   3
999                    3
1692                   3
375                    3
1858                   3
1527                   3
1779                   3
2470                   3
1817                   3
1591                   3
1129                   3
2017                   3
2257                   3
661                    3
1513                   3
1233                   3
1751                   3
1066                   3
2325                   3
1488                   3
1124                   3
2880                   3
1164                   3
1839                   3
2061                   3
994                    3
1307                   3
1469                   3
1832                   3
2550                   3
823                    3
1097                   3
1147                   3
1984                   3
3630 - 3800            3
3205                   3
1566                   3
1594                   3
829                    3
1553                   3
1919                   3
1426                   3
3630                   3
2503                   3
1478                   3
1653                   3
1121                   3
2292                   3
1694                   3

In [63]:
def preprocess_total_sqft(my_list):
    if len(my_list) == 1:
        
        try:
            return float(my_list[0])
        except:
            strings = ['Sq. Meter', 'Sq. Yards', 'Perch', 'Acres', 'Cents', 'Guntha', 'Grounds']
            split_list = re.split('(\d*.*\d)', my_list[0])[1:]
            area = float(split_list[0])
            type_of_area = split_list[1]
            
            if type_of_area == 'Sq. Meter':
                area_in_sqft = area * 10.7639
            elif type_of_area == 'Sq. Yards':
                area_in_sqft = area * 9.0
            elif type_of_area == 'Perch':
                area_in_sqft = area * 272.25
            elif type_of_area == 'Acres':
                area_in_sqft = area * 43560.0
            elif type_of_area == 'Cents':
                area_in_sqft = area * 435.61545
            elif type_of_area == 'Guntha':
                area_in_sqft = area * 1089.0
            elif type_of_area == 'Grounds':
                area_in_sqft = area * 2400.0
            return float(area_in_sqft)
        
    else:
        return (float(my_list[0]) + float(my_list[1]))/2.0

In [65]:
df['total_sqft'] = df.total_sqft.str.split('-').apply(preprocess_total_sqft)

In [66]:
df_num=df.drop(['Location','price'],1)

In [67]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [68]:
df_num = scaler.fit_transform(df_num,1)
df_num

array([[2.38095238e-02, 8.07316198e-04, 2.56410256e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [7.14285714e-02, 1.98882919e-03, 1.02564103e-01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [4.76190476e-02, 1.10116399e-03, 2.56410256e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.38095238e-02, 8.72360631e-04, 2.56410256e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.14285714e-02, 3.58739179e-03, 7.69230769e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 4.20110514e-04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [69]:
df_txt=df['Location']

In [70]:
# df_txt['Location'] = df_txt[df_txt.columns[0:]].apply(
#     lambda x: ','.join(x.dropna().astype(str)),
#     axis=1)

# df_txt.main.head(3)

In [71]:
# df_txt.head(20)

In [72]:
y=df['price']

In [73]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\welcome\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [74]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
vector = TfidfVectorizer(max_features = 3000, min_df = 1, max_df = 0.6,ngram_range = (1,2))
X_text = vector.fit_transform(df_txt).toarray()

In [76]:
X_text

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [77]:
X = np.concatenate((X_text,df_num),axis = 1)
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [78]:
X.shape

(13318, 3007)

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.10, random_state = 42)

In [80]:
from sklearn.ensemble import RandomForestRegressor

In [81]:
regr = RandomForestRegressor(n_jobs = 4, random_state = 42, n_estimators = 100, verbose = 1, max_features = 'auto')

In [82]:
regr.fit(X_train, y_train)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:  2.1min
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:  4.4min finished

RandomForestRegressor(n_jobs=4, random_state=42, verbose=1)

In [83]:
regr.score(X_train,y_train)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.3s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.6s finished

0.9497157733648984

In [85]:
import numpy as np
from sklearn import metrics

pred1 = regr.predict(X_test) 
rmse = np.sqrt(metrics.mean_squared_error(y_test, pred1)) 
print("RMSE : % f" %(rmse))

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed:    0.0s
[Parallel(n_jobs=4)]: Done 100 out of 100 | elapsed:    0.0s finished

RMSE :  61.891879

In [86]:
metrics.r2_score(y_test, pred1)

0.7950209182837843